"""Fixed engineering assumptions, distinct from experimental propeller measurements."""

SPECIFICATION = {
    "_id": "survey-vtol-range-v2",
    "payload_kg": 0.5,
    "battery_wh": 150.0,
    "battery_kg": 0.85,
    "reserve_fraction": 0.2,
    "hover_seconds": 90.0,
    "transition_seconds": 40.0,
    "transition_power_factor": 1.15,
    "max_mass_kg": 5.0,
    "rho": 1.225,
    "viscosity": 1.7894e-5,
    "gravity": 9.80665,
    "motor_efficiency": 0.85,
    "esc_efficiency": 0.97,
    "avionics_w": 12.0,
    "lift_motor_limit_w": 400.0,
    "cruise_motor_limit_w": 500.0,
    "battery_power_limit_w": 1600.0,
    "lift_prop_diameter_m": 0.4064,
    "cruise_prop_diameter_m": 0.3048,
    "lift_motor_mass_kg": 0.095,
    "cruise_motor_mass_kg": 0.14,
    "lift_prop_mass_kg": 0.045,
    "cruise_prop_mass_kg": 0.025,
    "other_hardware_kg": 0.30,
    "skin_areal_kg_m2": 0.09,
    "hover_thrust_ratio": 1.3,
    "stall_cl_limit": 1.1,
    "stall_speed_factor": 1.3,
    "static_margin_range": [0.05, 0.20],
    "max_elevator_deg": 15.0,
    "maneuver_g": 3.5,
    "landing_g": 3.0,
    "ultimate_factor": 1.5,
    "aluminium_e_pa": 69e9,
    "aluminium_allowable_pa": 200e6,
    "tip_deflection_span_fraction": 0.025,
    "payload_mission_km": 10.0,
    "payload_density_kg_m3": 1000.0,
    "min_prop_clearance_m": 0.02,
    "speed_retention": 0.95,
    "payload_retention": 0.95,
    "sources": [
        {
            "name": "UIUC experimental propeller maps",
            "url": "https://m-selig.ae.illinois.edu/props/volume-4/propDB-volume-4.html",
            "kind": "measurement",
        },
        {
            "name": "AeroSandbox VLM",
            "url": "https://aerosandbox.readthedocs.io/en/master/autoapi/aerosandbox/aerodynamics/aero_3D/vortex_lattice_method/",
            "kind": "solver",
        },
        {
            "name": "XFOIL",
            "url": "https://web.mit.edu/drela/Public/web/xfoil/xfoil_doc.txt",
            "kind": "solver",
        },
    ],
    "assumptions": "Hardware masses, power limits, motor efficiency, material allowables, battery and transition energy are frozen engineering assumptions, not measured aircraft performance.",
}
